import { GuessFeedback } from '@/types/game';

// In-memory data store for local dev execution with 100% reliability
const INITIAL_PLAYERS = [
  {
    id: 'player-virat-kohli-001',
    uuid: 'player-virat-kohli-001',
    displayName: 'Virat Kohli',
    fullName: 'Virat Kohli',
    shortName: 'V Kohli',
    initials: 'VK',
    gender: 'MALE',
    dateOfBirth: '1988-11-05',
    birthPlace: 'Delhi',
    birthCountry: 'India',
    nationality: 'Indian',
    countryCode: 'IN',
    playingEra: '2010s',
    isActive: true,
    isRetired: false,
    role: 'Top-order Batter',
    roleTags: 'Batter, Top-order Batter, Captain',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm medium',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: true,
    jerseyNumber: 18,
    debutTest: '2011',
    debutODI: '2008',
    debutT20I: '2010',
    careerSpan: '2008-Present',
    profileImage: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 1.5,
    popularityRank: 1,
    dataQualityScore: 99,
    aliases: [{ id: 'a1', alias: 'VK' }, { id: 'a2', alias: 'King Kohli' }],
    identifiers: [{ id: 'i1', sourceName: 'cricsheet', externalId: 'b78a9c21' }],
    competitions: [{ id: 'c1', competition: 'IPL' }, { id: 'c2', competition: 'Test' }, { id: 'c3', competition: 'ODI' }],
    statistics: [
      { format: 'TEST', matches: 113, runs: 8848, wickets: 0, battingAvg: 49.15, strikeRate: 55.56, hundreds: 29, fifties: 30, catches: 115 },
      { format: 'ODI', matches: 292, runs: 13848, wickets: 5, battingAvg: 58.67, strikeRate: 93.58, hundreds: 50, fifties: 72, catches: 152 },
      { format: 'T20I', matches: 125, runs: 4188, wickets: 4, battingAvg: 48.69, strikeRate: 137.04, hundreds: 1, fifties: 37, catches: 54 },
      { format: 'IPL', matches: 252, runs: 8004, wickets: 4, battingAvg: 38.66, strikeRate: 131.97, hundreds: 8, fifties: 55, catches: 110 },
    ],
  },
  {
    id: 'player-ellyse-perry-002',
    uuid: 'player-ellyse-perry-002',
    displayName: 'Ellyse Perry',
    fullName: 'Ellyse Alexandra Perry',
    shortName: 'E Perry',
    initials: 'EP',
    gender: 'FEMALE',
    dateOfBirth: '1990-11-03',
    birthPlace: 'Sydney',
    birthCountry: 'Australia',
    nationality: 'Australian',
    countryCode: 'AU',
    playingEra: '2010s',
    isActive: true,
    isRetired: false,
    role: 'Batting All-rounder',
    roleTags: 'All-rounder, Batting All-rounder',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm fast-medium',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: false,
    jerseyNumber: 8,
    debutTest: '2008',
    debutODI: '2007',
    debutT20I: '2008',
    careerSpan: '2007-Present',
    profileImage: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 2.5,
    popularityRank: 5,
    dataQualityScore: 98,
    aliases: [{ id: 'a3', alias: 'Pez' }],
    identifiers: [{ id: 'i2', sourceName: 'cricsheet', externalId: 'a12b34cd' }],
    competitions: [{ id: 'c4', competition: 'WPL' }, { id: 'c5', competition: 'WBBL' }],
    statistics: [
      { format: 'TEST', matches: 13, runs: 928, wickets: 38, battingAvg: 61.86, strikeRate: 46.2, hundreds: 2, fifties: 4, catches: 7 },
      { format: 'ODI', matches: 141, runs: 3852, wickets: 162, battingAvg: 50.68, strikeRate: 77.4, hundreds: 2, fifties: 34, catches: 48 },
    ],
  },
  {
    id: 'player-don-bradman-003',
    uuid: 'player-don-bradman-003',
    displayName: 'Sir Donald Bradman',
    fullName: 'Sir Donald George Bradman',
    shortName: 'D Bradman',
    initials: 'DG',
    gender: 'MALE',
    dateOfBirth: '1908-08-27',
    birthPlace: 'Cootamundra',
    birthCountry: 'Australia',
    nationality: 'Australian',
    countryCode: 'AU',
    playingEra: '1930s',
    isActive: false,
    isRetired: true,
    role: 'Top-order Batter',
    roleTags: 'Batter, Top-order Batter, Legend',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm leg spin',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: true,
    jerseyNumber: null,
    debutTest: '1928',
    careerSpan: '1928-1948',
    profileImage: 'https://images.unsplash.com/photo-1512719994953-eabf50895df7?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 3.0,
    popularityRank: 10,
    dataQualityScore: 100,
    aliases: [{ id: 'a4', alias: 'The Don' }],
    identifiers: [{ id: 'i3', sourceName: 'cricsheet', externalId: 'don_bradman' }],
    competitions: [{ id: 'c6', competition: 'Test' }],
    statistics: [
      { format: 'TEST', matches: 52, runs: 6996, wickets: 2, battingAvg: 99.94, strikeRate: 61.2, hundreds: 29, fifties: 13, catches: 32 },
    ],
  },
  {
    id: 'player-lasith-malinga-004',
    uuid: 'player-lasith-malinga-004',
    displayName: 'Lasith Malinga',
    fullName: 'Separamadu Lasith Malinga',
    shortName: 'L Malinga',
    initials: 'LM',
    gender: 'MALE',
    dateOfBirth: '1983-08-28',
    birthPlace: 'Galle',
    birthCountry: 'Sri Lanka',
    nationality: 'Sri Lankan',
    countryCode: 'SL',
    playingEra: '2000s',
    isActive: false,
    isRetired: true,
    role: 'Bowler',
    roleTags: 'Bowler, Fast Bowler, Sling Bowler',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm fast (Sling)',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: true,
    jerseyNumber: 99,
    debutTest: '2004',
    careerSpan: '2004-2020',
    profileImage: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 2.0,
    popularityRank: 12,
    dataQualityScore: 97,
    aliases: [{ id: 'a5', alias: 'Slinga Malinga' }],
    identifiers: [{ id: 'i4', sourceName: 'cricsheet', externalId: 'malinga_99' }],
    competitions: [{ id: 'c7', competition: 'IPL' }, { id: 'c8', competition: 'ODI' }],
    statistics: [
      { format: 'ODI', matches: 226, runs: 567, wickets: 338, battingAvg: 28.87, strikeRate: 77.4, hundreds: 0, fifties: 0, catches: 31 },
      { format: 'IPL', matches: 122, runs: 88, wickets: 170, battingAvg: 19.8, strikeRate: 130.0, hundreds: 0, fifties: 0, catches: 24 },
    ],
  },
  {
    id: 'player-rashid-khan-005',
    uuid: 'player-rashid-khan-005',
    displayName: 'Rashid Khan',
    fullName: 'Rashid Khan Arman',
    shortName: 'Rashid Khan',
    initials: 'RK',
    gender: 'MALE',
    dateOfBirth: '1998-09-20',
    birthPlace: 'Nangarhar',
    birthCountry: 'Afghanistan',
    nationality: 'Afghan',
    countryCode: 'AF',
    playingEra: '2010s',
    isActive: true,
    isRetired: false,
    role: 'Bowling All-rounder',
    roleTags: 'Bowler, Leg Spinner, Franchise Specialist',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm leg spin',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: true,
    jerseyNumber: 19,
    debutODI: '2015',
    careerSpan: '2015-Present',
    profileImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 2.2,
    popularityRank: 8,
    dataQualityScore: 96,
    aliases: [{ id: 'a6', alias: 'Rashid' }],
    identifiers: [{ id: 'i5', sourceName: 'cricsheet', externalId: 'rashid_19' }],
    competitions: [{ id: 'c9', competition: 'IPL' }, { id: 'c10', competition: 'BBL' }],
    statistics: [
      { format: 'T20I', matches: 92, runs: 430, wickets: 150, battingAvg: 14.3, strikeRate: 125.0, hundreds: 0, fifties: 0, catches: 30 },
    ],
  },
  {
    id: 'player-gerhard-erasmus-006',
    uuid: 'player-gerhard-erasmus-006',
    displayName: 'Gerhard Erasmus',
    fullName: 'Merwe Gerhard Erasmus',
    shortName: 'G Erasmus',
    initials: 'GE',
    gender: 'MALE',
    dateOfBirth: '1995-04-11',
    birthPlace: 'Windhoek',
    birthCountry: 'Namibia',
    nationality: 'Namibian',
    countryCode: 'NA',
    playingEra: '2010s',
    isActive: true,
    isRetired: false,
    role: 'Batting All-rounder',
    roleTags: 'Batter, All-rounder, Associate Leader',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm off spin',
    bowlingArm: 'Right',
    wicketkeeper: false,
    captain: true,
    jerseyNumber: 7,
    debutODI: '2019',
    careerSpan: '2019-Present',
    profileImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 7.2,
    popularityRank: 85,
    dataQualityScore: 94,
    aliases: [{ id: 'a7', alias: 'Erasmus' }],
    identifiers: [{ id: 'i6', sourceName: 'cricsheet', externalId: 'erasmus_nam' }],
    competitions: [{ id: 'c11', competition: 'ODI' }, { id: 'c12', competition: 'T20 World Cup' }],
    statistics: [
      { format: 'ODI', matches: 45, runs: 1680, wickets: 24, battingAvg: 43.07, strikeRate: 80.5, hundreds: 2, fifties: 13, catches: 22 },
    ],
  },
  {
    id: 'player-ms-dhoni-012',
    uuid: 'player-ms-dhoni-012',
    displayName: 'MS Dhoni',
    fullName: 'Mahendra Singh Dhoni',
    shortName: 'MS Dhoni',
    initials: 'MSD',
    gender: 'MALE',
    dateOfBirth: '1981-07-07',
    birthPlace: 'Ranchi',
    birthCountry: 'India',
    nationality: 'Indian',
    countryCode: 'IN',
    playingEra: '2000s',
    isActive: false,
    isRetired: true,
    role: 'Wicketkeeper Batter',
    roleTags: 'Wicketkeeper, Finisher, Captain, Legend',
    battingStyle: 'Right-hand batter',
    bowlingStyle: 'Right-arm medium',
    bowlingArm: 'Right',
    wicketkeeper: true,
    captain: true,
    jerseyNumber: 7,
    debutTest: '2005',
    careerSpan: '2004-2019',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop',
    difficultyScore: 1.2,
    popularityRank: 2,
    dataQualityScore: 100,
    aliases: [{ id: 'a8', alias: 'MSD' }, { id: 'a9', alias: 'Mahi' }, { id: 'a10', alias: 'Captain Cool' }],
    identifiers: [{ id: 'i7', sourceName: 'cricsheet', externalId: 'msd_07' }],
    competitions: [{ id: 'c13', competition: 'IPL' }, { id: 'c14', competition: 'ODI' }, { id: 'c15', competition: 'Test' }],
    statistics: [
      { format: 'ODI', matches: 350, runs: 10773, wickets: 1, battingAvg: 50.57, strikeRate: 87.56, hundreds: 10, fifties: 73, catches: 321 },
      { format: 'IPL', matches: 264, runs: 5243, wickets: 0, battingAvg: 39.13, strikeRate: 137.54, hundreds: 0, fifties: 24, catches: 152 },
    ],
  },
];

let sessionsStore: Record<string, any> = {};

export const prisma = {
  player: {
    findMany: async (args?: any) => {
      let list = [...INITIAL_PLAYERS];
      if (args?.where?.isRetired) list = list.filter((p) => p.isRetired);
      if (args?.where?.gender) list = list.filter((p) => p.gender === args.where.gender);
      if (args?.where?.countryCode) list = list.filter((p) => p.countryCode === args.where.countryCode);
      if (args?.take) list = list.slice(0, args.take);
      return list;
    },
    findUnique: async (args: any) => {
      return INITIAL_PLAYERS.find((p) => p.id === args.where.id || p.uuid === args.where.id) || null;
    },
    findFirst: async (args?: any) => {
      let list = [...INITIAL_PLAYERS];
      if (args?.where?.isRetired) list = list.filter((p) => p.isRetired);
      if (args?.where?.gender) list = list.filter((p) => p.gender === args.where.gender);
      if (args?.where?.displayName) list = list.filter((p) => p.displayName === args.where.displayName);
      if (args?.skip) list = list.slice(args.skip);
      return list[0] || INITIAL_PLAYERS[0];
    },
    count: async (args?: any) => INITIAL_PLAYERS.length,
    delete: async (args: any) => ({ success: true }),
  },

  dailyChallenge: {
    findFirst: async (_args?: any) => ({
      id: 'daily-284',
      challengeNumber: 284,
      challengeDate: '2026-09-05',
      player: INITIAL_PLAYERS[0],
    }),
  },

  gameSession: {
    create: async (args: any) => {
      const session = {
        id: args.data.sessionToken,
        sessionToken: args.data.sessionToken,
        mode: args.data.mode,
        targetPlayerId: args.data.targetPlayerId,
        targetPlayer: INITIAL_PLAYERS.find((p) => p.id === args.data.targetPlayerId) || INITIAL_PLAYERS[0],
        attemptsCount: 0,
        maxAttempts: 8,
        isCompleted: false,
        isWon: false,
      };
      sessionsStore[session.id] = session;
      return session;
    },
    findUnique: async (args: any) => sessionsStore[args.where.id] || null,
    update: async (args: any) => {
      if (sessionsStore[args.where.id]) {
        Object.assign(sessionsStore[args.where.id], args.data);
      }
      return sessionsStore[args.where.id];
    },
  },

  gameGuess: {
    create: async (args: any) => args.data,
  },

  playerAlias: {
    create: async (args: any) => args.data,
    updateMany: async (_args?: any) => ({ count: 1 }),
    createMany: async (_args?: any) => ({ count: 1 }),
  },

  playerIdentifier: {
    updateMany: async (_args?: any) => ({ count: 1 }),
  },

  dataSource: {
    findUnique: async (_args?: any): Promise<any> => null,
    create: async (args: any) => ({ id: 'ds-1', ...args.data }),
    update: async (_args?: any) => ({ success: true }),
  },

  dataImportJob: {
    create: async (args: any) => ({ id: 'job-1', ...args.data }),
    update: async (_args?: any) => ({ success: true }),
  },

  auditLog: {
    create: async (args: any) => args.data,
  },
};
