services:
  - type: web
    name: cricket-app
    env: node
    plan: free
    region: singapore
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
